version: '3.1'

services:
  db:
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wethenew

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  wethenew:
    build: ./
    depends_on: 
      - db
    restart: always
    ports:
      - 3000:3000